#!/bin/bash

echo "🍪 YouTube Cookie Extraction Script"
echo "=================================="

# Check if Python is available
if ! command -v python3 &> /dev/null; then
    echo "❌ Python3 is not installed. Please install Python3 first."
    exit 1
fi

# Install browser-cookie3 if not already installed
echo "📦 Installing browser-cookie3..."
pip3 install browser-cookie3 --break-system-packages

if [ $? -ne 0 ]; then
    echo "❌ Failed to install browser-cookie3"
    echo "Try running: sudo pip3 install browser-cookie3"
    exit 1
fi

echo "🔍 Extracting YouTube cookies from your browser..."

# Python script to extract cookies
python3 -c "
import browser_cookie3
import http.cookiejar
import os

try:
    # Try Chrome first
    cookies = browser_cookie3.chrome(domain_name='.youtube.com')
    print('✅ Found cookies from Chrome')
except:
    try:
        # Try Firefox
        cookies = browser_cookie3.firefox(domain_name='.youtube.com')
        print('✅ Found cookies from Firefox')
    except:
        try:
            # Try Edge
            cookies = browser_cookie3.edge(domain_name='.youtube.com')
            print('✅ Found cookies from Edge')
        except:
            print('❌ No cookies found. Make sure you are signed into YouTube in your browser.')
            exit(1)

# Save in Netscape format
with open('cookies.txt', 'w') as f:
    f.write('# Netscape HTTP Cookie File\n')
    f.write('# This file was automatically generated by the setup script\n')
    f.write('# Make sure you are signed into YouTube in your browser\n\n')
    
    cookie_count = 0
    for cookie in cookies:
        if '.youtube.com' in cookie.domain or 'youtube.com' in cookie.domain:
            f.write(f'{cookie.domain}\tTRUE\t{cookie.path}\t{\"TRUE\" if cookie.secure else \"FALSE\"}\t{cookie.expires}\t{cookie.name}\t{cookie.value}\n')
            cookie_count += 1

print(f'🍪 Extracted {cookie_count} YouTube cookies to cookies.txt')
print('✅ Cookie extraction completed successfully!')
"

if [ $? -eq 0 ]; then
    echo ""
    echo "🎉 Setup completed! You can now run the application:"
    echo "   npm start"
    echo ""
    echo "📝 Note: If you still get authentication errors, make sure you are signed into YouTube in your browser."
else
    echo ""
    echo "❌ Cookie extraction failed. Please try the manual method described in extract_cookies.md"
fi 